title: ""
description: Data Analyst | SQL | Power BI | Python

url: "https://arunkumar2541.github.io"
baseurl: "/portfolio"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "contrast"
masthead_title: ""

author:
  name: "Arunkumar Parameswaran"
  avatar: "/images/arun-photo.jpg"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
